import type { Category } from '../types/game';

/**
 * "Challenge" categories: unlike the freeform categories in categories.ts
 * (where players name anything belonging to a broad topic), each item here
 * is a specific, self-contained prompt — a math problem, a riddle, a
 * would-you-rather, a dare — shown on its own and solved/answered directly.
 * Free, app-wide (pack: 'quick-challenges'), first batch of ~50 per category.
 */
export const CHALLENGE_CATEGORIES: Category[] = [
  {
    id: 'quick-math',
    name: 'Quick Math',
    pack: 'quick-challenges',
    difficulty: 'easy',
    kind: 'challenge',
    items: [
      '6 + 12', '6 + 1', '5 + 3', '96 - 35', '49 + 24', '9 + 9', '379 + 368', '11 x 3', '11 + 21', '15 + 47',
      '77 / 11', '35 / 7', '11 x 8', '186 - 10', '1 + 1', '47 - 35', '29 + 31', '20 + 36', '10 x 9', '5 x 2',
      '2 x 9', '64 / 8', '15 / 5', '10 x 11', '9 x 9', '181 + 273', '10 x 12', '10 x 6', '6 x 12', '105 - 25',
      '234 + 215', '113 + 201', '120 / 10', '45 - 30', '58 - 15', '10 + 32', '94 - 31', '48 + 40', '481 + 188', '30 + 18',
      '70 / 7', '122 - 3', '20 / 10', '16 + 16', '43 - 19', '80 / 8', '28 - 16', '11 x 10', '61 - 18', '400 + 420',
    ],
  },
  {
    id: 'country-puzzles',
    name: 'Country Puzzles',
    pack: 'quick-challenges',
    difficulty: 'medium',
    kind: 'challenge',
    items: [
      'Name a country that starts with A and ends with A',
      'Name a country that starts with B and ends with A',
      'Name a country that starts with C and ends with A',
      'Name a country that starts with G and ends with A',
      'Name a country that starts with M and ends with A',
      'Name a country that starts with N and ends with A',
      'Name a country that starts with R and ends with A',
      'Name a country that starts with I and ends with A',
      'Name a country that starts with E and ends with A',
      'Name a country that starts with L and ends with A',
      'Name a country that starts with V and ends with A',
      'Name a country that starts with Z and ends with A',
      'Name a country that starts with U',
      'Name a country that starts with P',
      'Name a country that starts with T',
      'Name a country that starts with F',
      'Name a country that starts with H',
      'Name a country that starts with J',
      'Name a country that starts with O',
      'Name a country that starts with Q',
      'Name a country that starts with K',
      'Name a country that starts with S',
      'Name a country that ends with N',
      'Name a country that ends with Y',
      'Name a country that ends with D',
      'Name a country that ends with L',
      'Name a country that ends with O',
      'Name a country that ends with S',
      'Name a country with exactly four letters',
      'Name a country with exactly five letters',
      'Name a landlocked country',
      'Name an island nation',
      'Name a country that borders the USA',
      'Name a country in South America',
      'Name a country that used to have a different name',
      'Name a country with more than one official language',
      'Name a country whose flag has a star on it',
      'Name a country whose flag has no straight lines dividing colors',
      'Name a country that spans two continents',
      'Name a country smaller than a US state',
      'Name a country you need a visa to visit as a tourist',
      'Name a country that has never won an Olympic gold medal',
      'Name a country that drives on the left',
      'Name the largest country by area',
      'Name the most populous country',
      'Name a country with a monarchy today',
      'Name a country that shares a name with a US city',
      'Name a country in the Southern Hemisphere',
      'Name a country whose capital is not its largest city',
      'Name a country that has a desert',
    ],
  },
  {
    id: 'would-you-rather-quick',
    name: 'Would You Rather',
    pack: 'quick-challenges',
    difficulty: 'easy',
    kind: 'challenge',
    items: [
      'Would you rather be able to fly or be invisible?',
      'Would you rather always be 10 minutes late or 20 minutes early?',
      'Would you rather give up your phone for a week or your shoes for a month?',
      'Would you rather have a rewind button or a pause button for your life?',
      'Would you rather never eat cheese again or never eat chocolate again?',
      'Would you rather live without music or without TV?',
      'Would you rather always speak your mind or never speak again?',
      'Would you rather be famous for something embarrassing or unknown forever?',
      'Would you rather fight one horse-sized duck or 100 duck-sized horses?',
      'Would you rather always have to sing instead of speak or dance everywhere you walk?',
      'Would you rather live in a treehouse or a houseboat?',
      'Would you rather have unlimited money or unlimited time?',
      'Would you rather lose your sense of smell or your sense of taste?',
      'Would you rather never use social media again or never watch another movie?',
      'Would you rather be the funniest person in the room or the smartest?',
      'Would you rather explore space or the deep ocean?',
      'Would you rather always have to whisper or always have to shout?',
      'Would you rather have no internet or no air conditioning/heating?',
      'Would you rather be able to talk to animals or speak every human language?',
      'Would you rather relive your favorite year or skip straight to age 40?',
      'Would you rather have to hop everywhere or crawl everywhere?',
      'Would you rather give up sleep or give up food (safely, forever)?',
      'Would you rather live one very long life or several short ones?',
      'Would you rather always know when someone is lying or always get away with lying?',
      'Would you rather be stuck in traffic or stuck at the airport?',
      'Would you rather have a personal chef or a personal driver?',
      'Would you rather be too hot forever or too cold forever?',
      'Would you rather read minds or predict the future?',
      'Would you rather live without hot showers or without your phone?',
      'Would you rather have everyone you meet like you or one person truly understand you?',
      'Would you rather be able to skip Mondays or always have three-day weekends but shorter vacations?',
      'Would you rather never be able to lie or never be able to keep a secret?',
      'Would you rather have a photographic memory or be a genius at math?',
      'Would you rather live in the city or the countryside?',
      'Would you rather always order for the table or never get to choose the restaurant?',
      'Would you rather have free flights for life or free hotels for life?',
      'Would you rather be able to teleport or freeze time?',
      'Would you rather lose all your old photos or never take new ones again?',
      'Would you rather have to tell everyone the truth about what you think of them, right now?',
      'Would you rather live without air conditioning or without your car?',
      'Would you rather be the best player on a losing team or the worst player on a winning team?',
      'Would you rather have a rewind button on embarrassing moments or a fast-forward button on boring ones?',
      'Would you rather never be cold again or never be hot again?',
      'Would you rather give up desserts or give up fried food?',
      "Would you rather always have to say what you're thinking or never speak your opinion again?",
      'Would you rather have the ability to breathe underwater or survive without oxygen on land only?',
      'Would you rather be famous online or respected in your actual life?',
      'Would you rather have unlimited vacation days or unlimited sick days?',
      'Would you rather live 100 years in the past or 100 years in the future?',
      'Would you rather never have to do laundry again or never have to do dishes again?',
      'Would you rather be able to change one decision from your past or know one thing about your future?',
    ],
  },
  {
    id: 'truth-or-dare-quick',
    name: 'Truth or Dare',
    pack: 'quick-challenges',
    difficulty: 'easy',
    kind: 'challenge',
    items: [
      'TRUTH: What is the most embarrassing thing that has happened to you at a party?',
      'DARE: Do your best impression of someone else in the room.',
      'TRUTH: What is a rule you’ve broken and never got caught?',
      'DARE: Let the group pick your profile picture for a week.',
      'TRUTH: What is the pettiest thing you’ve ever been mad about?',
      'DARE: Talk in an accent until your next turn.',
      'TRUTH: What is the last lie you told?',
      'DARE: Do 15 jumping jacks right now.',
      'TRUTH: What app do you spend the most time on and why?',
      'DARE: Text a random contact "guess who".',
      'TRUTH: What’s a food you pretend to like but actually don’t?',
      'DARE: Let someone else style your hair for the next ten minutes.',
      'TRUTH: What’s the most trouble you got into as a kid?',
      'DARE: Speak only in questions for the next two minutes.',
      'TRUTH: What is a habit you wish you could break?',
      'DARE: Do your best dance move for 10 seconds.',
      'TRUTH: What’s something you’re secretly proud of?',
      'DARE: Try to lick your elbow.',
      'TRUTH: What’s the worst gift you’ve ever received?',
      'DARE: Let the group draw on your hand with a pen.',
      'TRUTH: What’s a fear you have that people would find surprising?',
      'DARE: Sing the chorus of a song someone else picks.',
      'TRUTH: What’s the longest you’ve gone without showering?',
      'DARE: Balance a spoon on your nose for 10 seconds.',
      'TRUTH: What’s a text you regret sending?',
      'DARE: Do an impression of a baby for 30 seconds.',
      'TRUTH: What’s your most-used emoji and why?',
      'DARE: Let someone else post something (harmless) to your story.',
      'TRUTH: What’s something you’ve never told your parents?',
      'DARE: Walk like a crab for 10 steps.',
      'TRUTH: What’s the weirdest dream you remember having?',
      'DARE: Speak in movie quotes only for two minutes.',
      'TRUTH: What’s a compliment you received that you’ll never forget?',
      'DARE: Let someone read your last three texts out loud.',
      'TRUTH: What’s something you regret not doing?',
      'DARE: Do your best celebrity impression.',
      'TRUTH: What’s the most embarrassing song on your playlist?',
      'DARE: Try to make the group laugh without using words.',
      'TRUTH: What’s a small thing that instantly puts you in a bad mood?',
      'DARE: Hold a plank for 20 seconds.',
      'TRUTH: What’s the last thing you Googled?',
      'DARE: Let someone give you a new nickname for the rest of the game.',
      'TRUTH: What’s something you pretend to understand but don’t?',
      'DARE: Do your best impression of an animal of the group’s choice.',
      'TRUTH: Who’s the last person you stalked on social media?',
      'DARE: Say the alphabet backwards.',
      'TRUTH: What’s a nickname you’ve had that you hated?',
      'DARE: Let the group choose your next meal.',
      'TRUTH: What’s something on your bucket list you haven’t told anyone?',
      'DARE: Talk without moving your lips for 30 seconds.',
    ],
  },
  {
    id: 'most-likely-to-quick',
    name: 'Most Likely To',
    pack: 'quick-challenges',
    difficulty: 'easy',
    kind: 'challenge',
    items: [
      'Most likely to become a millionaire',
      'Most likely to become famous',
      'Most likely to cry during a movie',
      'Most likely to survive a zombie apocalypse',
      'Most likely to forget their own birthday',
      'Most likely to become president (or prime minister)',
      'Most likely to be late to their own wedding',
      'Most likely to win an argument with no facts',
      'Most likely to fall asleep at a party',
      'Most likely to start a business',
      'Most likely to get lost using GPS',
      'Most likely to become an influencer',
      'Most likely to eat the same meal every day for a year',
      'Most likely to talk their way out of a speeding ticket',
      'Most likely to cry laughing in a serious meeting',
      'Most likely to move to another country',
      'Most likely to become a stand-up comedian',
      'Most likely to accidentally reply-all to an email',
      'Most likely to win the lottery and lose the ticket',
      'Most likely to adopt every stray animal they see',
      'Most likely to be the last one to leave a party',
      'Most likely to know all the words to a song they claim to hate',
      'Most likely to become a professional athlete',
      'Most likely to text the wrong person something embarrassing',
      'Most likely to write a bestselling book',
      'Most likely to skip a workout for pizza',
      'Most likely to end up on a reality TV show',
      'Most likely to become the boss one day',
      'Most likely to forget where they parked',
      'Most likely to survive being stranded on a desert island',
      'Most likely to plan a surprise party and spoil it',
      'Most likely to talk during a movie',
      'Most likely to become a teacher',
      'Most likely to win a game show',
      'Most likely to send a text and immediately regret it',
      'Most likely to be a millionaire by 30',
      'Most likely to fall for a prank',
      'Most likely to have the messiest room',
      'Most likely to become a chef',
      'Most likely to give the best advice',
      'Most likely to cancel plans last minute',
      'Most likely to sleep through an alarm',
      'Most likely to start a group chat that never stops',
      'Most likely to become a lawyer',
      'Most likely to run a marathon on a whim',
      'Most likely to win an eating contest',
      'Most likely to become a YouTuber',
      'Most likely to remember everyone’s birthday',
      'Most likely to get a tattoo they regret',
      'Most likely to be the peacemaker in a fight',
      'Most likely to become famous for a viral video',
    ],
  },
  {
    id: 'rhyme-time',
    name: 'Rhyme Time',
    pack: 'quick-challenges',
    difficulty: 'easy',
    kind: 'challenge',
    items: [
      'Say a word that rhymes with CAT', 'Say a word that rhymes with DOG', 'Say a word that rhymes with TREE',
      'Say a word that rhymes with LIGHT', 'Say a word that rhymes with CHAIR', 'Say a word that rhymes with STAR',
      'Say a word that rhymes with RAIN', 'Say a word that rhymes with SHOE', 'Say a word that rhymes with CAKE',
      'Say a word that rhymes with BOAT', 'Say a word that rhymes with PHONE', 'Say a word that rhymes with BALL',
      'Say a word that rhymes with SNAKE', 'Say a word that rhymes with MOUSE', 'Say a word that rhymes with BEE',
      'Say a word that rhymes with COAT', 'Say a word that rhymes with FROG', 'Say a word that rhymes with KING',
      'Say a word that rhymes with NIGHT', 'Say a word that rhymes with DOOR', 'Say a word that rhymes with BIKE',
      'Say a word that rhymes with SUN', 'Say a word that rhymes with MOON', 'Say a word that rhymes with FISH',
      'Say a word that rhymes with BEAR', 'Say a word that rhymes with GOAT', 'Say a word that rhymes with CLOCK',
      'Say a word that rhymes with TOWN', 'Say a word that rhymes with CROWN', 'Say a word that rhymes with BLUE',
      'Say a word that rhymes with GREEN', 'Say a word that rhymes with SAND', 'Say a word that rhymes with HAND',
      'Say a word that rhymes with WALL', 'Say a word that rhymes with SMILE', 'Say a word that rhymes with HEART',
      'Say a word that rhymes with PARTY', 'Say a word that rhymes with GAME', 'Say a word that rhymes with FLAME',
      'Say a word that rhymes with ROCK', 'Say a word that rhymes with LAKE', 'Say a word that rhymes with RACE',
      'Say a word that rhymes with FACE', 'Say a word that rhymes with SHIRT', 'Say a word that rhymes with SHORT',
      'Say a word that rhymes with LOUD', 'Say a word that rhymes with CROWD', 'Say a word that rhymes with BRIGHT',
      'Say a word that rhymes with SIGHT', 'Say a word that rhymes with TOWN HALL', 'Say a word that rhymes with SNOW',
    ],
  },
  {
    id: 'finish-the-phrase',
    name: 'Finish the Phrase',
    pack: 'quick-challenges',
    difficulty: 'medium',
    kind: 'challenge',
    items: [
      'Finish the phrase: Better late than ___', 'Finish the phrase: Actions speak louder than ___',
      'Finish the phrase: When in Rome, do as the ___', 'Finish the phrase: The early bird catches the ___',
      'Finish the phrase: Don’t count your chickens before they ___', 'Finish the phrase: A picture is worth a thousand ___',
      'Finish the phrase: Practice makes ___', 'Finish the phrase: Curiosity killed the ___',
      'Finish the phrase: Every cloud has a silver ___', 'Finish the phrase: Honesty is the best ___',
      'Finish the phrase: Two wrongs don’t make a ___', 'Finish the phrase: The grass is always greener on the other ___',
      'Finish the phrase: Don’t judge a book by its ___', 'Finish the phrase: It takes two to ___',
      'Finish the phrase: Absence makes the heart grow ___', 'Finish the phrase: Better safe than ___',
      'Finish the phrase: You can’t have your cake and eat it ___', 'Finish the phrase: Out of sight, out of ___',
      'Finish the phrase: When the going gets tough, the tough get ___', 'Finish the phrase: The pen is mightier than the ___',
      'Finish the phrase: Don’t put all your eggs in one ___', 'Finish the phrase: A watched pot never ___',
      'Finish the phrase: Birds of a feather flock ___', 'Finish the phrase: Rome wasn’t built in a ___',
      'Finish the phrase: You reap what you ___', 'Finish the phrase: Where there’s smoke, there’s ___',
      'Finish the phrase: Once bitten, twice ___', 'Finish the phrase: The apple doesn’t fall far from the ___',
      'Finish the phrase: Slow and steady wins the ___', 'Finish the phrase: Don’t bite the hand that ___',
      'Finish the phrase: An apple a day keeps the ___ away', 'Finish the phrase: Beggars can’t be ___',
      'Finish the phrase: All that glitters is not ___', 'Finish the phrase: The squeaky wheel gets the ___',
      'Finish the phrase: Blood is thicker than ___', 'Finish the phrase: A penny saved is a penny ___',
      'Finish the phrase: Too many cooks spoil the ___', 'Finish the phrase: When one door closes, another one ___',
      'Finish the phrase: You can lead a horse to water, but you can’t make it ___',
      'Finish the phrase: Fool me once, shame on you; fool me twice, shame on ___',
      'Finish the phrase: The best things in life are ___', 'Finish the phrase: Every dog has its ___',
      'Finish the phrase: Don’t cry over spilled ___', 'Finish the phrase: A chain is only as strong as its weakest ___',
      'Finish the phrase: Strike while the iron is ___', 'Finish the phrase: There’s no place like ___',
      'Finish the phrase: A rolling stone gathers no ___', 'Finish the phrase: What goes around comes ___',
      'Finish the phrase: The proof is in the ___', 'Finish the phrase: Time heals all ___',
      'Finish the phrase: Laughter is the best ___',
    ],
  },
  {
    id: 'this-or-that',
    name: 'This or That',
    pack: 'quick-challenges',
    difficulty: 'easy',
    kind: 'challenge',
    items: [
      'This or that: Beach or mountains?', 'This or that: Coffee or tea?', 'This or that: Sweet or salty?',
      'This or that: Cats or dogs?', 'This or that: Morning or night?', 'This or that: Books or movies?',
      'This or that: Summer or winter?', 'This or that: Pizza or tacos?', 'This or that: City or countryside?',
      'This or that: Text or call?', 'This or that: Window seat or aisle seat?', 'This or that: Netflix or a night out?',
      'This or that: Rock or pop?', 'This or that: Pancakes or waffles?', 'This or that: Camping or a hotel?',
      'This or that: Early bird or night owl?', 'This or that: Comedy or horror?', 'This or that: Driving or being driven?',
      'This or that: Board games or video games?', 'This or that: Spicy or mild?', 'This or that: Concert or festival?',
      'This or that: Handwritten or typed?', 'This or that: Save it or spend it?', 'This or that: Plan ahead or wing it?',
      'This or that: Big party or small gathering?', 'This or that: Chocolate or vanilla?', 'This or that: Shower or bath?',
      'This or that: Sunrise or sunset?', 'This or that: Karaoke or trivia night?', 'This or that: Road trip or flight?',
      'This or that: Instagram or TikTok?', 'This or that: Cook at home or eat out?', 'This or that: Sneakers or sandals?',
      'This or that: Loud music or quiet music?', 'This or that: Team sports or solo sports?', 'This or that: Rain or snow?',
      'This or that: A long walk or a workout?', 'This or that: Reading a review or trusting your gut?',
      'This or that: Group project or solo project?', 'This or that: Front row or back row?', 'This or that: Save the best for last or get it over with first?',
      'This or that: A big breakfast or a big dinner?', 'This or that: Fiction or nonfiction?', 'This or that: Streaming or the movie theater?',
      'This or that: One best friend or a big friend group?', 'This or that: Silence or background noise while working?',
      'This or that: New experiences or familiar favorites?', 'This or that: Aisle browsing or a shopping list?',
      'This or that: Talk it out or sleep on it?', 'This or that: Give advice or just listen?',
    ],
  },
  {
    id: 'quick-trivia',
    name: 'Quick Trivia',
    pack: 'quick-challenges',
    difficulty: 'medium',
    kind: 'challenge',
    items: [
      'How many continents are there?', 'How many colors are in a rainbow?', 'How many strings does a standard guitar have?',
      'How many players are on a soccer team on the field at once?', 'How many sides does a hexagon have?',
      'How many bones are in the adult human body (roughly)?', 'How many minutes are in a full day?',
      'How many planets are in our solar system?', 'How many time zones does mainland USA have?',
      'How many squares are on a chessboard?', 'How many strings does a violin have?', 'What is the freezing point of water in Celsius?',
      'How many legs does a spider have?', 'How many players are on a basketball team on the court at once?',
      'How many weeks are in a year (roughly)?', 'How many chambers does the human heart have?',
      'How many Great Lakes are there?', 'How many symphonies did Beethoven complete?', 'How many moons does Earth have?',
      'How many teeth does an adult human typically have?', 'How many primary colors are there?', 'How many keys are on a standard piano?',
      'How many innings are in a standard baseball game?', 'How many holes are played in a standard round of golf?',
      'How many sides does a stop sign have?', 'How many degrees are in a right angle?',
      'How many countries border the USA?', 'How many oceans are there?', 'How many muscles does it take to smile (roughly)?',
      'How many letters are in the English alphabet?', 'How many wonders of the ancient world are there?',
      'How many stars are on the US flag?', 'How many players are on a volleyball team on the court at once?',
      'How many rings are on the Olympic flag?', 'How many colors are the Olympic rings?',
      'What year did the year 2000 come after?', 'How many quarters make up an NFL football game?',
      'How many minutes are in a standard soccer match (not counting extra time)?', 'How many suits are in a standard deck of cards?',
      'How many cards are in a standard deck (no jokers)?', 'How many sides does a dodecahedron have?',
      'How many senses do humans traditionally have?', 'How many days are in a leap year?',
      'How many degrees are in a full circle?', 'How many strings does a standard bass guitar have?',
      'How many players are on a hockey team on the ice at once?', 'How many wheels does a standard bicycle have?',
      'How many wheels does a tricycle have?', 'How many sides does a triangle have?', 'How many zeros are in one million?',
    ],
  },
  {
    id: 'letter-challenge',
    name: 'Letter Challenge',
    pack: 'quick-challenges',
    difficulty: 'medium',
    kind: 'challenge',
    items: [
      'Name an animal that starts with B', 'Name a fruit that starts with P', 'Name a movie genre that starts with C',
      'Name a color that starts with G', 'Name a sport that starts with S', 'Name a country that starts with I',
      'Name an animal that starts with L', 'Name a food that starts with T', 'Name a job that starts with D',
      'Name a city that starts with M', 'Name an animal that starts with E', 'Name a drink that starts with C',
      'Name a fruit that starts with M', 'Name a sport that starts with H', 'Name a movie genre that starts with H',
      'Name an animal that starts with T', 'Name a vegetable that starts with C', 'Name a job that starts with T',
      'Name a color that starts with P', 'Name a country that starts with C', 'Name an animal that starts with G',
      'Name a dessert that starts with C', 'Name a sport that starts with B', 'Name an animal that starts with O',
      'Name a fruit that starts with A', 'Name a job that starts with N', 'Name a city that starts with L',
      'Name an animal that starts with S', 'Name a color that starts with R', 'Name a vegetable that starts with P',
      'Name a country that starts with S', 'Name an animal that starts with W', 'Name a dessert that starts with P',
      'Name a sport that starts with T', 'Name a fruit that starts with G', 'Name a job that starts with P',
      'Name an animal that starts with F', 'Name a movie genre that starts with A', 'Name a drink that starts with W',
      'Name a color that starts with B', 'Name an animal that starts with R', 'Name a vegetable that starts with O',
      'Name a country that starts with T', 'Name an animal that starts with D', 'Name a job that starts with E',
      'Name a fruit that starts with C', 'Name a sport that starts with G', 'Name an animal that starts with K',
      'Name a dessert that starts with I', 'Name a city that starts with P',
    ],
  },
];
